spring:
  profiles:
    active: usage_message
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: a5k4CooL

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000
